### ISSUE TITLE
Duplication in project description

### ISSUE THREAD

**Issue by SpyrosRoum** [SharieRhea/SharieRhea.github.io#2]
Hi, you've written the same text twice in the description for the nyEats project [here](https://github.com/SharieRhea/SharieRhea.github.io/blob/6c1930b8d008123e7baa800075231dcb82df7377/index.html#L112-L115)

**Comment by SharieRhea** [comment]
Thank you for the catch! I will update the description as well as the icon for NY Eats soon.
