### ISSUE TITLE
Couple of spelling errors

### ISSUE THREAD

**Issue by codebywinston** [SharieRhea/SharieRhea.github.io#3]
Hi, love your site! I noticed two typos that I thought you might like to fix:

1. In the first sentence of the third paragraph under #about, "Univerisity" should be "University".
2. In the last sentence of that same paragraph above, "fantasty" should be "fantasy".

**Comment by SharieRhea** [comment]
Thank you for catching those! I'll be sure to fix it for the next update.

**Comment by SharieRhea** [comment]
Should be fixed now! Thanks again for bringing it to my attention.
